language: node_js
node_js:
  - "7.2.1"

sudo: required
addons:
  chrome: stable

before_script:
  - npm install
  - ./node_modules/.bin/selenium-standalone install
  - sleep 10

script:
  - ./nightwatch -e chrome-headless
