matrix:
  include:
    - language: ruby
      - "2.2.0"

      script:
        - cd app && bundle install
        - rackup &

    - language: node_js
      node_js:
        - "6.10.1"

      before_script:
        - npm install

      script:
        - ./nightwatch -e chrome-headless

  notifications:
    email:
      - paullittlebury@gmail.com
